### ISSUE TITLE
Documentation Should Mention that `us-east-1` ACM Certificates Are Required

### ISSUE THREAD

**Issue by mojeto** [cloudposse/terraform-aws-cloudfront-s3-cdn#10]
Hi, 
I have configuration as follow 
```
provider "aws" {
  region     = "ap-southeast-2"
}

module "cloudfront-s3-cdn" {
  source  = "cloudposse/cloudfront-s3-cdn/aws"
  version = "0.1.4"

  namespace        = "${var.namespace}"
  stage            = "${var.stage}"
  name             = "${var.name}"
  aliases          = "${var.aliases}"
  parent_zone_id   = "${var.hosted_domain_id}"
  acm_certificate_arn = "${var.acm_certificate_arn}"
}

variable "acm_certificate_arn" {
  type = "string"
  default = "arn:aws:acm:ap-southeast-2:....:certificate/......."
```

When I execute plan I get an error 
```
Error: Error applying plan:

1 error(s) occurred:

* module.cloudfront-s3-cdn.aws_cloudfront_distribution.default: 1 error(s) occurred:

* aws_cloudfront_distribution.default: InvalidViewerCertificate: The specified SSL certificate doesn't exist, isn't in us-east-1 region, isn't valid, or doesn't include a valid certificate chain.
        status code: 400, request id: .......
```

I've created the certificate in Sydney region and certificate arn reflex that, but execution tries to find it in us-east-1 and fails.

I have tried configure 
```
// based on https://stackoverflow.com/questions/45027175/how-to-specify-a-acm-certificate-in-a-specific-region-for-a-data-source

provider "aws" {
  region = "ap-southeast-2"
  alias = "sydney"
}

data "aws_acm_certificate" "domain_certificate" {
  provider = "aws.sydney"
  domain   = "my.domain.net"
  statuses = ["ISSUED"]
}
```
and the `terraform plan` find the certificate and fetch it's data. But `terraform apply` fails with the same error as above.  

How can I configure `cloudfront-s3-cdn` module to uses certificate in different than us-east-1 region?

**Comment by aknysh** [comment]
@mojeto 
thank you for testing and submitting the issue.
I think what you have is related to how AWS operates. Although ACM is supported in many regions, to use a certificate with CloudFront, it should be requested only in US East (N. Virginia) region.

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cnames-and-https-requirements.html
> If you want to require HTTPS between viewers and CloudFront, you must change the AWS region to US East (N. Virginia) in the AWS Certificate Manager console before you request or import a certificate.
> If you want to require HTTPS between CloudFront and your origin, and you're using an ELB load balancer as your origin, you can request or import a certificate in any region.

https://docs.aws.amazon.com/acm/latest/userguide/acm-regions.html
> To use an ACM Certificate with Amazon CloudFront, you must request or import the certificate in the US East (N. Virginia) region. ACM Certificates in this region that are associated with a CloudFront distribution are distributed to all the geographic locations configured for that distribution.

https://stackoverflow.com/questions/37289994/aws-certificate-manager-do-regions-matter

This is an AWS restriction, and you need to request the same cert in `us-east-1`.

**Comment by osterman** [comment]
@aknysh is correct. This is a fundamental requirement of CloudFront.

**Comment by mojeto** [comment]
@aknysh and @osterman thank you guys. I didn't know that. I've spent too much time checking the code is right and forgot to check AWS limitations. I suggest pointing these limitation out in `Generating ACM Certificate` in README.md. It would help me.

**Comment by osterman** [comment]
Ya, that's a good suggestion. I'm going to rename the issue to reflect that.

**Comment by aknysh** [comment]
@mojeto 
we'll update `README`, thanks

**Comment by aknysh** [comment]
@mojeto 
we updated `README` about using SSL cert with CloudFront.
Merged into `master`.
https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/releases/tag/0.1.5
