### ISSUE TITLE
BucketAlreadyOwnedByYou:

### ISSUE THREAD

**Issue by sergioUjo** [cloudposse/terraform-aws-cloudfront-s3-cdn#126]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
It's the first time I run this module, currently I am using terraform 0.14.5, and when I do I receive the folowing error: 

![image](https://user-images.githubusercontent.com/28688122/106494390-459ff800-64b2-11eb-8935-8246d5996a24.png)

My main.tf: 

![image](https://user-images.githubusercontent.com/28688122/106494495-67997a80-64b2-11eb-890c-e4ffea81ada5.png)

## Expected Behavior
Resources created without any error.

**Comment by nitrocode** [comment]
Looks like you're trying to create a bucket that already exists ? 

Are you trying to create a separate bucket or reuse an existing bucket ?

**Comment by Nuru** [comment]
Closing this issue as stale. If you can reproduce it with the current version of this module, and are not trying to create a bucket that already exists, please open a new issue.

**Comment by busla** [comment]
Could this be re-opened?

I get the same error when using the following params:

```terraform
data "aws_route53_zone" "this" {
  name = var.zone_name
}

# Custom module, could probably use the Cloudposse cloudfront acm feature
module "acm" {
  source      = "../../modules/acm"
  domain_name = var.zone_name
  zone_id     = data.aws_route53_zone.this.id
  providers   = {
    aws = aws.us
  }
}


module "cdn" {
  source  = "cloudposse/cloudfront-s3-cdn/aws"
  version = "0.82.2"

  namespace                 = "foo"
  stage                     = "dev"
  name                      = "bar"
  aliases                   = [var.zone_name, "*.${var.zone_name}"]
  dns_alias_enabled         = true
  parent_zone_id            = data.aws_route53_zone.this.id
  website_enabled           = true
  acm_certificate_arn       = module.acm.certificate_arn

  deployment_principal_arns = {
    "${var.runner_arn}" = [""]
  }
  depends_on = [module.acm]
}
```

**Comment by busla** [comment]
Even though I disable logging it still get the same error.

```terraform
# ...
  s3_access_logging_enabled = false
  cloudfront_access_logging_enabled = false
# ...
```

**Comment by busla** [comment]
Ok, I am retarded.

This has nothing todo with the module, there was a resource in another file that I missed 😆 

I can show myself out.
