### ISSUE TITLE
missing `attributes` Variable

### ISSUE THREAD

**Issue by mojeto** [cloudposse/terraform-aws-cloudfront-s3-cdn#13]
I found `attributes` Variable in README.md defined as

Name | Default | Description | Required
------|---------|------------|----------
attributes | [] | Additional attributes (e.g. policy or role) | No

but it isn't defined in `variables.tf`

**Comment by osterman** [comment]
@aknysh can you take a look at this?

**Comment by aknysh** [comment]
@mojeto 
thanks for submitting the issue.
fixed and merged to master
https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/releases/tag/0.1.7
