### ISSUE TITLE
Unable to update CDN settings when using custom_origins

### ISSUE THREAD

**Issue by chitopunk** [cloudposse/terraform-aws-cloudfront-s3-cdn#135]
## Describe the Bug
After updating a value in a current custom_origins object, terraform throws error of missing `custom_headers` that currently is not being used.

## Expected Behavior
Apply changes without failure.

## Steps to Reproduce
1. Go to: the description of the `custom_origins` and update any value `origin_read_timeout`
2. Run `terraform plan`
```
The given value is not suitable for child module variable "custom_origins"
defined at .terraform/modules/cdn/variables.tf:385,1-26: element 0: attribute
"custom_headers": element 0: attributes "name" and "value" are required.
```
## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: ```Darwin 19.6.0 Darwin Kernel Version 19.6.0; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64```
 - Version `10.15.7`

## Additional Context

I've also added an empty `custom_headers = [{}]` clause, but this throws random errors..

```
The given value is not suitable for child module variable "custom_origins"
defined at .terraform/modules/cdn/variables.tf:385,1-26: element 0: attribute
"origin_path": string required.

The given value is not suitable for child module variable "custom_origins"
defined at .terraform/modules/cdn/variables.tf:385,1-26: element 0: attribute
"domain_name": string required.
```

this happens with master branch, so I switched back to `0.48.1`
```terraform
module "cdn" {

  source                   = "git::https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn.git?ref=0.48.1"
  ... 
}
```

**Comment by msmagoo87** [comment]
@chitopunk I am unable to recreate this locally. Can you share which version of TF you're running, please?

**Comment by chitopunk** [comment]
@msmagoo87 my terraform version is.. 
```
Terraform v0.13.5
```

I share some part o f my custom_headers settings..

```terraform
  custom_origins = [{
    domain_name = "${lookup(local.api_gw_dns, local.environment)}.${lookup(local.main_dns_zone_name, local.environment)}"
    origin_id   = "api-${local.environment}-v2"
    origin_path = "/v1"
    custom_origin_config = {
      http_port                = 80
      https_port               = 443
      origin_protocol_policy   = "https-only"
      origin_ssl_protocols     = ["TLSv1.2"]
      origin_keepalive_timeout = 30
      origin_read_timeout      = 30
    }
  }]
```

**Comment by msmagoo87** [comment]
> @msmagoo87 my terraform version is..
> 
> ```
> Terraform v0.13.5
> ```
> 
> I share some part o f my custom_headers settings..
> 
> ```terraform
>   custom_origins = [{
>     domain_name = "${lookup(local.api_gw_dns, local.environment)}.${lookup(local.main_dns_zone_name, local.environment)}"
>     origin_id   = "api-${local.environment}-v2"
>     origin_path = "/v1"
>     custom_origin_config = {
>       http_port                = 80
>       https_port               = 443
>       origin_protocol_policy   = "https-only"
>       origin_ssl_protocols     = ["TLSv1.2"]
>       origin_keepalive_timeout = 30
>       origin_read_timeout      = 30
>     }
>   }]
> ```
This is without setting `customer_headers = []`. When you change it to this you still get the error you indicated?
```
custom_origins = [{
    domain_name = "${lookup(local.api_gw_dns, local.environment)}.${lookup(local.main_dns_zone_name, local.environment)}"
    origin_id   = "api-${local.environment}-v2"
    origin_path = "/v1"
    custom_headers = []
    custom_origin_config = {
      http_port                = 80
      https_port               = 443
      origin_protocol_policy   = "https-only"
      origin_ssl_protocols     = ["TLSv1.2"]
      origin_keepalive_timeout = 30
      origin_read_timeout      = 30
    }
  }]
  ```

**Comment by Nuru** [comment]
The Terraform requirement is that if you supply a `custom_origins` object, you must fill in _all_ the fields. 

This appears to be a Terraform bug (https://github.com/hashicorp/terraform/issues/27010) regarding the bad error message. 

Closing as `invalid`
