### ISSUE TITLE
No apple m1 support due to use of deprecated "hashicorp/template" provider

### ISSUE THREAD

**Issue by joepjoosten** [cloudposse/terraform-aws-cloudfront-s3-cdn#139]
This module uses the deprecated "registry.terraform.io/hashicorp/template" provider. This provider doesn't get updated anymore by hashicorp (https://github.com/hashicorp/terraform-provider-template/blob/master/README.md).

This means that this won't be updated to go 1.16, and thus no support for macbooks with apple m1 .

**Comment by wchatx** [comment]
Thanks for the work on this @nitrocode! But doesn't [this](https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/blob/master/versions.tf#L10) need to be removed too? Trying to get 0.53.0 working on my M1 but no luck.

**Comment by nitrocode** [comment]
Ah you're right. Good catch
