### ISSUE TITLE
Configure S3 to support `website` mode

### ISSUE THREAD

**Issue by mojeto** [cloudposse/terraform-aws-cloudfront-s3-cdn#14]
Hi,
How can I use your module to configure S3 origin as `Static website hosting` ?
It's disabled by default. 
The main reason for me is `Static website hosting` allows mapping 'folder' and 'subfolder' url paths to `index.html` file in given folder. 
i.e  `/contact/`  -> `/contact/index.html`

With current S3 setup I get `/contact/` Error `NoSuchKey`.

**Comment by osterman** [comment]
As implemented, it might not support that. Our client's use-case was to specifically to serve static assets. The module could probably be extended to add that support.

In the meantime, you can achieve the same thing by using our 2 other modules:
- https://github.com/cloudposse/terraform-aws-s3-website
- https://github.com/cloudposse/terraform-aws-cloudfront-cdn

Basically, create the S3 "website" bucket and then accelerate with our generic `cloudfront-cdn` module which will work with any website.

**Comment by mojeto** [comment]
Thanks for a good work you have done on those modules and for pointing me to correct direction too. 

I leave this issue open in a case you want to implement this feature in future, but feel free to close it as I'll use the other two modules you suggested.

Cheers.

**Comment by osterman** [comment]
thanks @mojeto! I'll keep it open for now. Makes sense that we should add support for `website` mode.

**Comment by geota** [comment]
I tried combining the above modules and didnt find it satisfactory for a couple of reasons:

1) s3-website only allows for acl "public-read", id like to avoid this and serve the assets only through the CDN using aws_cloudfront_origin_access_identity resource like you do currently.
2) there is no ability to inject your own buckets which then leads to two log buckets being created (one per each module)

Im going to attempt to submit a PR here for this.

**Comment by aknysh** [comment]
addressed in https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/releases/tag/0.15.0
