### ISSUE TITLE
Regional domains show `s3` instead of `s3-website` resulting in misconfiguration

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/terraform-aws-cloudfront-s3-cdn#148]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
Looks like the static bucket hack removal PR https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/pull/143 caused an issue where `-website` is missing from the domain

This ticket is created on behalf of @syphernl 

https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/pull/143/files#r604661084

> This change seems to have broken the "s3-website" functionality. It now wants to change the origin domain_name from
XXXXX.s3-website.eu-west-1.amazonaws.com to XXXXX.s3.eu-west-1.amazonaws.com which results in an AccessDenied when loading the domain.

## Expected Behavior
No errors

## Steps to Reproduce
Use `eu-west-1` region with `var.website_enabled`

## Solution Proposals
* Perhaps it would be better to use [`website_domain`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#website_domain) or `website_endpoint` outputs?
    * `website_endpoint` seems correct according to the comments below
* Is there a reason to use the non regional endpoint vs the regional endpoint? I wonder if the `website_domain` covers this.
    * `website_endpoint` seems to cover this
* Override the origin `domain_name` via an input in case this comes up again 
    * might be overkill

**Comment by syphernl** [comment]
@nitrocode Looks good! 

One minor thing I noticed is that it wants to replace the existing 
`REDACTED.s3-website.eu-west-1.amazonaws.com` into 
`REDACTED.s3-website-eu-west-1.amazonaws.com` (a dash instead of a dot between `s3-website` and the region) but this is due to the way things were generated prior to v0.55.

Since both the dash and dot-variants are working the same this is an acceptable change IMHO.
