### ISSUE TITLE
Error using existing S3 bucket in 0.59.0

### ISSUE THREAD

**Issue by pearsonhenri** [cloudposse/terraform-aws-cloudfront-s3-cdn#151]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
Using 0.59.0 of this module, if I specify an existing S3 bucket (which also has an existing bucket policy) and run `terraform apply`, the operation fails with
```

Error: Error creating S3 bucket: BucketAlreadyExists: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.
	status code: 409, request id: 3PMBHS08MF98NFQW, host id: sLfaifwFHwD9biX57oJgzueRkMuCBARUTwoawf2MQaJACVEEQ9m863hkwH781UuFJ0klApMABzU=

  on .terraform/modules/inspetor.inspetor_mongo_staging.logs/main.tf line 1, in resource "aws_s3_bucket" "default":
   1: resource "aws_s3_bucket" "default" {



Error: Error putting S3 policy: InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, PutBucketPolicyInput.Bucket.


  on .terraform/modules/inspetor.inspetor_mongo_staging/main.tf line 79, in resource "aws_s3_bucket_policy" "default":
  79: resource "aws_s3_bucket_policy" "default" {

```

I tried re-running `terraform apply` thereafter, but then I get a rather inscrutable error:
```
Error: origin.0.origin_id must not be empty, got

  on .terraform/modules/inspetor.inspetor_mongo_staging/main.tf line 194, in resource "aws_cloudfront_distribution" "default":
 194: resource "aws_cloudfront_distribution" "default" {
```

(I'm assuming that means an empty string is being passed for `origin_id`)

## Expected Behavior
Well... it should work? 😅 

## Steps to Reproduce
1. Create an S3 bucket
2. Instantiate this module via
```
module "my_module" {
  source                        = "cloudposse/cloudfront-s3-cdn/aws"
  version                       = "0.59.0"

  origin_bucket                 = "my.bucket.name"
  override_origin_bucket_policy = false
  aliases                       = ["my.alias.net"]
  dns_alias_enabled             = true
  parent_zone_id                = var.my_zone_id

  acm_certificate_arn           = var.my_acm_arn
}
```
3. Run `terraform apply`

## Environment (please complete the following information):
```
terraform --version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/archive v2.1.0
+ provider registry.terraform.io/hashicorp/aws v3.35.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/vault v2.18.0
+ provider registry.terraform.io/mongodb/mongodbatlas v0.8.2
+ provider registry.terraform.io/terraform-providers/docker v2.7.2
```

**Comment by jamengual** [comment]
@syphernl may be related to your PR?

**Comment by syphernl** [comment]
@jamengual @pearsonhenri ISTM that the logging bucket already exists, and that Terraform errors on that, since it refers to `inspetor.inspetor_mongo_staging.logs`.
This module only handles an existing _origin_ bucket, for logging one will be generated based on the tags.

**Comment by pearsonhenri** [comment]
Thanks for the replies guys. @syphernl I don't think it's that, because the bucket currently has access logging disabled. I can enable it, but then I need to specify a logging bucket, which from what your saying sounds like Terraform won't properly handle?

**Comment by pearsonhenri** [comment]
Unless you're suggesting that Terraform is trying to create a logging bucket called `inspetor.inspetor_mongo_staging.logs`, but it already exists (it does not exist yet).

**Comment by pearsonhenri** [comment]
Ooph but yeah I'm kinda stumped here, I can't even interact with this module now because Terraform errors in the planning phase now with the whole 
```
Error: origin.0.origin_id must not be empty, got

  on .terraform/modules/inspetor.inspetor_mongo_staging/main.tf line 194, in resource "aws_cloudfront_distribution" "default":
 194: resource "aws_cloudfront_distribution" "default" {
``` 
thing

**Comment by syphernl** [comment]
> Unless you're suggesting that Terraform is trying to create a logging bucket called `inspetor.inspetor_mongo_staging.logs`, but it already exists (it does not exist yet).

The particular ID I mentioned is the module name you are using with `.logs` appendage, which refers to the [logs "module"](https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/blob/master/main.tf#L154) reference within the s3-cdn module. 
As your example doesn't pass in any context (tags etc) it would likely try to generate a bucket named `logs` rather than `my-cool-app-prod-logs`. 
S3 buckets need to be globally unique, if it tries to create a bucket that already exists it will fail.

There are two ways of fixing this:
- Pass along the a  `context` and to this resource. 
- Disable CloudFront access logging by setting `logging_enabled` to `false`.

**Comment by pearsonhenri** [comment]
Ah, cool--ok I tried setting `logging_enabled` to `false` and recreating the module, however my `apply`s are still failing with ```
Error: origin.0.origin_id must not be empty, got

  on .terraform/modules/inspetor.inspetor_mongo_staging/main.tf line 194, in resource "aws_cloudfront_distribution" "default":
 194: resource "aws_cloudfront_distribution" "default" {
```

So maybe that's a separate issue?

**Comment by syphernl** [comment]
Can you verify whether it works in the previous version, `v0.58.1`?

**Comment by pearsonhenri** [comment]
Yeah actually when I recreated just now it was on 0.58.1

**Comment by pearsonhenri** [comment]
So just to be clear, my updated configuration looks like this:
```
module "my_module" {
  source                        = "cloudposse/cloudfront-s3-cdn/aws"
  version                       = "0.58.1"

  origin_bucket                 = "my.s3.bucket"
  override_origin_bucket_policy = false
  aliases                       = ["my.cname.net"]
  dns_alias_enabled             = true
  logging_enabled               = false
  parent_zone_id                = var.my_zone_id

  acm_certificate_arn           = var.my_acm_arn
}
```

and applying this configuration results in the mentioned error and even prevents me from being able to run `terraform plan` subsequently

**Comment by syphernl** [comment]
ISTM the `origin_id` is based on the context, something like this should probably make it work:
```hcl
module "my_module" {
  source                        = "cloudposse/cloudfront-s3-cdn/aws"
  version                       = "0.58.1"
  
  origin_bucket                 = "my.s3.bucket"
  override_origin_bucket_policy = false
  aliases                       = ["my.cname.net"]
  dns_alias_enabled             = true
  logging_enabled               = false
  parent_zone_id                = var.my_zone_id

  acm_certificate_arn           = var.my_acm_arn
  
  name                          = "cdn"
  stage                         = "prod"
  namespace                     = "eg"
}
```

**Comment by pearsonhenri** [comment]
@syphernl nice, looks like that was indeed the problem! Would be great if you could include that in the docs--the README lists an example like this for importing an existing S3 bucket:
```
module "cdn" {
  source = "cloudposse/cloudfront-s3-cdn/aws"
  # Cloud Posse recommends pinning every module to a specific version
  # version     = "x.x.x"

  origin_bucket     = "eg-prod-app"
  aliases           = ["assets.cloudposse.com"]
  dns_alias_enabled = true
  parent_zone_name  = "cloudposse.com"
}
``` 
(without name/stage/namespace args), which is what got me down this wayward path.

**Comment by pearsonhenri** [comment]
Ooph, one more problem @syphernl: I removed the `override_origin_bucket_policy = false` setting so that the module could properly grant access for the Cloudfront distribution to the S3 bucket, but then I run into this issue:
```

Error: Error putting S3 policy: InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, PutBucketPolicyInput.Bucket.


  on .terraform/modules/inspetor.inspetor_mongo_staging/main.tf line 79, in resource "aws_s3_bucket_policy" "default":
  79: resource "aws_s3_bucket_policy" "default" {
```

Seems like my provided bucket name isn't getting passed along somewhere?

**Comment by pearsonhenri** [comment]
Well, I'm not _totally_ sure what the error is there, but looking at the policy that the module is trying to put, it looks like my existing bucket gets replaced by the name/stage/namespace combo instead of the actual bucket I want to use:
```
{
    "Statement" : [{
        "Action"    : "s3:GetObject",
        "Effect"    : "Allow",
        "Principal" : {
            "AWS" : "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity E2AMSMCXH9W59V"
        },
        "Resource"  : "arn:aws:s3:::{namespace}.{name}-{stage}/*",
        "Sid"       : "S3GetObjectForCloudFront"
    },
    {
        "Action"    : "s3:ListBucket",
        "Effect"    : "Allow",
        "Principal" : {
            "AWS" : "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity E2AMSMCXH9W59V"
        },
        "Resource"  : "arn:aws:s3:::{namespace}.{name}-{stage}",
        "Sid"       : "S3ListBucketForCloudFront"
    }
    ],
    "Version"   : "2012-10-17"
}
```

**Comment by pearsonhenri** [comment]
Hi there--any update on the above? I'm manually copy-pasting a bucket policy to work around this for now

**Comment by syphernl** [comment]
@pearsonhenri I've created a draft [PR](https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/pull/155) that could fix that. Could you see if that works for you?
For that you'll need to modify the `source` to:

```
  source      = "git::https://github.com/syphernl/terraform-aws-cloudfront-s3-cdn?ref=2c3635e9cf7258f2bd642dc9c2616bb2b6ecc3b7"
```

Don't forget to run `terraform init` afterwards to pull in the changes.

**Comment by syphernl** [comment]
@pearsonhenri Another [issue](https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/issues/152) has been created for that with a [PR](https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/issues/154) to fix it.

**Comment by richstokes** [comment]
Still running into this issue on `0.75.0`

**Comment by CodechCFA** [comment]
Oof. Over a year and a half later, that same code snippet in the readme sent me down a rabbit hole with this same error message. Adding `name` fixed the problem.
