### ISSUE TITLE
Support S3 regional redirect  (new AWS feature)

### ISSUE THREAD

**Issue by Jamie-BitFlight** [cloudposse/terraform-aws-cloudfront-s3-cdn#16]
## what

Add support for regional S3 endpoint

## why

* CloudFront now allows specifying S3 regional endpoint when creating S3 origin. 
* By default, CloudFront still uses global endpoint convention on console but one can manually enter the regional endpoint and avoid redirects.

Would you mind updating the TF to use the regional endpoint in cloudfront?

**Comment by osterman** [comment]
@Jamie-BitFlight sounds interesting. Would can take a look at it. 

Could you link us to (a) the announcement (b) terraform documentation for the feature? If it was recently, added, it might not yet be supported by the `terraform-aws-provider`.

**Comment by Jamie-BitFlight** [comment]
Sorry it was from this AWS employee saying it:
https://forums.aws.amazon.com/message.jspa?messageID=830100#830100
I have tested changing the url within cloudfront manually in the console and it is currently working too.

**Comment by osterman** [comment]
Thanks @Jamie-BitFlight! At this time we cannot prioritize the feature as it's not been requested by one of our clients. We'll leave the issue open. If someone submits a PR, we'll promptly review it.

**Comment by ebarault** [comment]
@Jamie-BitFlight @osterman 
Hi, 
If i'm right this is not related to `terraform-aws-provider` support: all you to do is update the s3 bucket url to use the regional api instead of the global one.

For example:
http://my-bucket.s3.amazonaws.com/ -> http://my-bucket.s3.eu-west-3.amazonaws.com

see https://docs.aws.amazon.com/general/latest/gr/rande.html for the full list of regional endpoints

**Comment by osterman** [comment]
thanks @ebarault! @Jamie-BitFlight let me know if this works for you.

**Comment by kitsunde** [comment]
FYI there's a PR to expose the regional endpoint so it doesn't need to be constructed: https://github.com/terraform-providers/terraform-provider-aws/pull/4556

**Comment by osterman** [comment]
Thanks @kitsunde. Keep us posted.

**Comment by Jamie-BitFlight** [comment]
I've added a constructed regional endpoint option in this pull request. https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/pull/17

**Comment by Jamie-BitFlight** [comment]
wohooooooooooooo!

**Comment by Jamie-BitFlight** [comment]
6th march - till 26 june : RIP Issue 16
