### ISSUE TITLE
Inaccurate `origin.domain_name` of main bucket in CF distribution 

### ISSUE THREAD

**Issue by entr** [cloudposse/terraform-aws-cloudfront-s3-cdn#165]
## Describe the Bug
Looks like #160 reverted changes from #149 and the `domain_name` of my distribution origin is incomplete `s3-website.eu-central-1.amazonaws.com` with `website_enabled = true`.
Looking at the source of `0.66.0` I can't see the changes from #149 where you started using `website_endpoint` instead of `bucket_regional_domain_name`.

## Expected Behavior
origin's `domain_name` should start with the bucket name.

## Environment:
 - OS: Ubuntu 20.04
 - Version 0.66.0

**Comment by nitrocode** [comment]
cc: @Nuru looks like a regression

**Comment by entr** [comment]
Looks like #166 has fixed just that.
