### ISSUE TITLE
Error if Origin Bucket has MFA Delete Enabled

### ISSUE THREAD

**Issue by sgtoj** [cloudposse/terraform-aws-cloudfront-s3-cdn#189]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
If MFA Delete has been enabled on the origin bucket, this module attempts to set `mfa_delete` to `false`. Doing so causes an error:

```
AccessDenied: Mfa Authentication must be used for this request
```

## Expected Behavior
Ignore changes to MFA delete configuration.  

## Steps to Reproduce
1. deploy this module
2. enable mfa delete on the origin bucket
3. make changes to the module's configuration to trigger deployment on next deployment
4. deploy changes
5. See error

## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment (please complete the following information):
- terraform v1.0.9
- terraform aws provider v3.63.0

## Additional Context
N/A

**Comment by Nuru** [comment]
We are not going to support MFA delete on See buckets. See details [here](https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/pull/190#issuecomment-1050796576).
