### ISSUE TITLE
Bug in configuration of allowed origins for S3 bucket

### ISSUE THREAD

**Issue by ToROxI** [cloudposse/terraform-aws-cloudfront-s3-cdn#22]
According to [S3 CORS configuration Amazon documentation](https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html) there is a bug in configuration of allowed origins.

Example from documentation shows that each CORS rule need to consist only one AllowedOrigin parameter:
```
<CORSConfiguration>
 <CORSRule>
   <AllowedOrigin>http://www.example1.com</AllowedOrigin>

   <AllowedMethod>PUT</AllowedMethod>
   <AllowedMethod>POST</AllowedMethod>
   <AllowedMethod>DELETE</AllowedMethod>

   <AllowedHeader>*</AllowedHeader>
 </CORSRule>
 <CORSRule>
   <AllowedOrigin>http://www.example2.com</AllowedOrigin>

   <AllowedMethod>PUT</AllowedMethod>
   <AllowedMethod>POST</AllowedMethod>
   <AllowedMethod>DELETE</AllowedMethod>

   <AllowedHeader>*</AllowedHeader>
 </CORSRule>
 <CORSRule>
   <AllowedOrigin>*</AllowedOrigin>
   <AllowedMethod>GET</AllowedMethod>
 </CORSRule>
</CORSConfiguration>
```

In case if assign `example.com` value  to the `cors_allowed_origins` variable, result will be next:
```
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>example.com</AllowedOrigin>
    <AllowedOrigin>some.otherdomain.com</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <MaxAgeSeconds>3600</MaxAgeSeconds>
    <ExposeHeader>ETag</ExposeHeader>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```

This is the cause of "floating" bug, when sometimes calls works fine, but other times returns a CORS error.

**Comment by osterman** [comment]
Wow, thanks for posting this @ToROxI . I recall having a similar issue to what you describe.

**Comment by osterman** [comment]
We should be able to rewrite this another way.

We can use a technique similar to what we do here: 

https://github.com/cloudposse/terraform-aws-cloudfront-cdn/blob/master/examples/wordpress/main.tf#L49-L56

To create multiple maps. 

We can't fix this now. If you have time to submit a PR, we'll promptly review it!

Also, you're welcome to join our community at https://slack.cloudposse.com
