### ISSUE TITLE
Update Instructions to use our ACM Module

### ISSUE THREAD

**Issue by osterman** [cloudposse/terraform-aws-cloudfront-s3-cdn#26]
## what
* Use `terraform-aws-acm-request-certificate` instead of `aws` cli

## why
* 100% native terraform, no cli necessary

## references
* https://github.com/cloudposse/terraform-aws-acm-request-certificate

**Comment by x80486** [comment]
Left a comment on issue 55. It has an almost complete example, except for the variables and so on. If the problem described can be fixed I can help with this one since it's almost the same text/code.

**Comment by nitrocode** [comment]
I see your issue comment here https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/issues/55#issuecomment-711108119 which is helpful. 

Here is a minimum example that we could add to the `README`

```hcl
module "acm_request_certificate" {
  source = "cloudposse/acm-request-certificate/aws"
  # Cloud Posse recommends pinning every module to a specific version
  # version = "x.x.x"
  domain_name                       = "example.com"
  subject_alternative_names         = ["*.example.com"]
  process_domain_validation_options = true
  ttl                               = "300"
}

module "cdn" {
  source = "cloudposse/cloudfront-s3-cdn/aws"
  # Cloud Posse recommends pinning every module to a specific version
  # version     = "x.x.x"
  namespace         = "eg"
  stage             = "prod"
  name              = "app"
  aliases           = ["assets.cloudposse.com"]
  dns_alias_enabled = true
  parent_zone_name  = "cloudposse.com"

  acm_certificate_arn = module.acm_request_certificate.arn

  depends_on = [module.acm_request_certificate]
}
```
