### ISSUE TITLE
Lambda function association doesn't set mandatory fields

### ISSUE THREAD

**Issue by fbdo** [cloudposse/terraform-aws-cloudfront-s3-cdn#37]
Hi CloudPosse team,
Great job with your reusable Terraform modules.

I am trying to setup a static website using this module, and all in all I succeed, but now I would like to setup a Lambda@Edge function to rewrite "/" to "/index.html".

Following the instructions on https://aws.amazon.com/blogs/compute/implementing-default-directory-indexes-in-amazon-s3-backed-amazon-cloudfront-origins-using-lambdaedge/, I came up with the solution shown in my repo: https://github.com/fbdo/aws-terraform-site/blob/master/website/main.tf.

Your documentation says you expect a list in "lambda_function_association" and looking at your code, and at Terraform documentation, I can see this parameter should be a list of configuration blocks. Right now my code is doing:

```hcl
  lambda_function_association = [{
    lambda_arn = "${aws_lambda_function.rewrite.qualified_arn}"
    event_type = "origin-request"
  }]
```

But no success, everytime I run my Terraform code I see the errors:
```bash
Error: module.cdn.aws_cloudfront_distribution.default: "default_cache_behavior.0.lambda_function_association.0.event_type": required field is not set

Error: module.cdn.aws_cloudfront_distribution.default: "default_cache_behavior.0.lambda_function_association.0.lambda_arn": required field is not set
```

Is this a bug or I am missing something here?

**Comment by osterman** [comment]
Hrmm I think @joshmyers has seen an error like this recently. Can you comment?

**Comment by aknysh** [comment]
@joshmyers  can you please address the comments?

@fbdo  if you know how to fix it, can you open a PR?
thanks

**Comment by sbuljac** [comment]
@fbdo I am pretty sure this is an issue with Terraform, interpolation doesn't work properly if you pass variables in an object that is part of the list to a module. A workaround is to hardcode lambda_arn value, I know, it suks.

**Comment by aknysh** [comment]
@fbdo  you can test two things:

1. Remove `lambda_arn = "${aws_lambda_function.rewrite.qualified_arn}"` from the object and just leave `event_type = "origin-request"` to check what @sbuljac suggested

2. In some cases TF does not flatten list of lists. You can update `lambda_function_association = ["${var.lambda_function_association}"]` to make it `lambda_function_association = "${var.lambda_function_association}" and see if that helps

**Comment by kskewes** [comment]
1. This didn't work for me.
2. This didn't work for me. Type specification requires list of objects.

With Terraform 0.12.13 we were able to do this.

```
  lambda_function_association = [{
    include_body = false
    lambda_arn   = aws_lambda_function.rewrite.qualified_arn
    event_type   = "origin-request"
  }]
```

Note `include_body` was required, either true or false.

For the lambda function (HUGO static site) used this: https://github.com/digital-sailors/standard-redirects-for-cloudfront

**Comment by nitrocode** [comment]
Yep I can confirm. This worked for me as well.

```hcl
  lambda_function_association = [
    {
      event_type   = "origin-request"
      include_body = false
      lambda_arn   = data.aws_lambda_function.request.arn
    },
    {
      event_type   = "viewer-response"
      include_body = false
      lambda_arn   = data.aws_lambda_function.response.arn
    },
  ]
```
