### ISSUE TITLE
Help with defining custom_error_responses

### ISSUE THREAD

**Issue by ppawlowski** [cloudposse/terraform-aws-cloudfront-s3-cdn#40]
Hello Gents,

I am struggling with defining custom_error_responses using your module. Can you please guide how to create custom error response with values kept in one variable:
```
"error_code" = 404
"response_code" = 200  
"response_page_path" = "/index.html"
```

Thank you in advance.

**Comment by ppawlowski** [comment]
Ok, with the trial-and-error approach I figured it out.
For someone, who will face the same confusion level as I, the module variable should be defined as follows:

```
custom_error_response = [
    {
      "error_code"          = 500
      "response_code"       = 200
      "response_page_path"  = "/error.html"
    }
]
```
Multiple error responses should be placed in multiple maps inside the list.

**Comment by jcf** [comment]
For anyone coming across this issue in future, you need to include the `error_caching_min_ttl` too:

``` hcl
custom_error_response = [
  {
    "error_caching_min_ttl" = 3600,
    "error_code"            = 500,
    "response_code"         = 500,
    "response_page_path"    = "/error.html",
  },
  {
    "error_caching_min_ttl" = 3600,
    "error_code"            = 404,
    "response_code"         = 404,
    "response_page_path"    = "/404.html",
  },
]
```

I've deployed these custom response objects to Cloudfront today without issue. Hope that helps! :bow:

**Comment by filipemcg** [comment]
Also valid:

```tf
custom_error_response {
        error_caching_min_ttl = 86400
        error_code = 404
        response_code = 200
        response_page_path = "/index.html"
 }

  custom_error_response {
        error_caching_min_ttl = 86400
        error_code = 403
        response_code = 200
        response_page_path = "/index.html"
 }
```

**Comment by Jao-Steven-Rey-C** [comment]
This is the snippet I am using:

custom_error_response {
    error_code            = 404
    response_page_path    = "/error.html"
    #response_code         = 404
    error_caching_min_ttl = 300
  }
  
   So How to I make Terraform display my error.html file instead of a website that has this message:
   
![Screenshot (238)](https://github.com/user-attachments/assets/46c12019-90e9-4670-b803-cf5db01780cc)

**Comment by ravirneni** [comment]
When response_page_path  is set to  "/index.html"  what would be the path it looks for?
For example if CloudFront  request url  is https://s3content.test.com/s3folder/s3path.html  => would the error file path is: https://cloufront-1.test.com/index.html
