### ISSUE TITLE
Configuration to create S3 bucket as encrypted

### ISSUE THREAD

**Issue by jcheatham** [cloudposse/terraform-aws-cloudfront-s3-cdn#42]
Hi, we'd like to use this module but due to various reasons (like SOC compliance) we need an encrypted S3 bucket.  Would it be worth making a PR to add that configuration here, or is it too weird/non-standard and we should just go fork ourselves?  Thanks!

**Comment by aknysh** [comment]
encryption was added in https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/releases/tag/0.14.0
