### ISSUE TITLE
How to use with Angular JS webapp released in S3 bucket

### ISSUE THREAD

**Issue by archenroot** [cloudposse/terraform-aws-cloudfront-s3-cdn#53]
Hi guys,

I really like your modules! Would you help me how to use this module with Angular + node js application which is released in S3 bucket in tar.gz via our Jenkins build process?

Thank you very much.

Ladislav

**Comment by aknysh** [comment]
static website support was added in https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/releases/tag/0.15.0
This will allow uploading website assets (unzipped, not in `tar.gz`) to the S3 bucket and use as static website with CDN.
