### ISSUE TITLE
Add support for `ordered_cache_behavior`

### ISSUE THREAD

**Issue by dmattia** [cloudposse/terraform-aws-cloudfront-s3-cdn#62]
I would like to handle the caching of some files differently from others.

In my particular case, this means handling `*.html` paths to not be cached at all.

My favorite option would be something like:

```hcl
variable "caching_blacklist" {
  type = set(string)
  default = []
  description = "Paths of objects that should never be cached for any HTTP methods"
}
```

where I could specify `caching_blacklist = ["*.html"]` in my vars, but more cases would be covered by covering all ordered_cache_behavior settings, with something like:

```hcl
variable "ordered_cache_behavior" {
  type = list(object({
    path_pattern = string
    allowed_methods = string
    ...
  }))
  default = []
  description = "..."
}
```

**Comment by CarpathianUA** [comment]
+1
