### ISSUE TITLE
Support IPv6

### ISSUE THREAD

**Issue by dimaqq** [cloudposse/terraform-aws-cloudfront-s3-cdn#64]
Full disclosure: IANAE
Obligatory major kudos for making this module :)

I've set up a CDN using this module, and here's the result:
* CloudFront distribution got created with IPv6 enabled
* Route53 alias got created in some such way that the new hostname resolves on IPv4 but not IPv6

[Edit: Public MRE removed because we've patched around that]

**Comment by dimaqq** [comment]
@michaelaw320 tracked it down to https://github.com/cloudposse/terraform-aws-route53-alias/blob/29b479ad0a5666b0ce2da13a82ca3dc4c9251eca/main.tf#L11

**Comment by dmattia** [comment]
I can work on this today

**Comment by dmattia** [comment]
Just opened a PR in terraform-aws-route53-alias that is blocking work on this repo: https://github.com/cloudposse/terraform-aws-route53-alias/pull/18

Once/if that's merged, I can add a variable in this repo to make use of the new functionality

**Comment by dmattia** [comment]
This can now be closed @aknysh

**Comment by dimaqq** [comment]
Awesome, works now :)
One tidbit is that there are now 2 flags to set up IPv6:
* `is_ipv6_enabled`
* `ipv6_enabled`

Still beggars can't be choosers :)
