### ISSUE TITLE
CORS configuration is being ignored at all.

### ISSUE THREAD

**Issue by fog1985** [cloudposse/terraform-aws-cloudfront-s3-cdn#69]
Hey guys,

It just doesn't create any CORS configuration for the S3 bucket. 
Though is already created. Like it exists before CloudFormation creation. 
Not sure if it makes a difference. 

Here is the code:
```
module "cloudfront_s3_cdn" {
  source              = "git::https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn.git?ref=0.11.0"
  acm_certificate_arn = var.cloudfront_acm_cert
  aliases             = ["assets.aws.example.net"]
  stage               = var.aws_env
  name                = var.product
  parent_zone_id      = var.hosted_zone
  origin_bucket       = var.cloudfront_s3_origin_bucket
  origin_path         = var.cloudfront_s3_origin
  allowed_methods     = ["GET","HEAD", "OPTIONS"]
  // use_regional_s3_endpoint = true
  origin_force_destroy     = false

  cors_allowed_origins     = ["*.example.net","*.www.example.net"]
  cors_allowed_methods     = ["GET", "HEAD", "OPTIONS"]
  cors_allowed_headers     = ["*"]
  cors_expose_headers      = ["ETag"]

  wait_for_deployment      = false
  additional_bucket_policy = var.additional_bucket_policy
}
```
Terraform version:
```
terraform --version                                                              (git)-[master]
Terraform v0.12.9
```
AWS provider version:
```
provider "aws" {
  region  = var.aws_region
  profile = var.aws_profile
  version = "~> 2.37.0"
}
```

**Comment by dmattia** [comment]
To me, it makes sense that the s3 specific parameters would only apply if the s3 bucket was being newly created.

Unfortunately, even if we wanted to allow updating the CORS of existing buckets, terraform makes that difficult.

To be able to control the CORS on an s3 bucket in terraform, you need to manage the s3 resource in that module, meaning to accomplish what you're asking you'd need to `terraform import` the bucket into the terraform state of this module. If you're managing that s3 bucket in some other module already, that would be problematic as you never want the same resource managed by multiple terraform modules.

So in your case, I think the easiest options are to:
1) Update the CORS for the origin bucket outside of this module, ideally in some other module that manages your bucket
2) Import the bucket state into this module, then do not use the `origin_bucket` var. You'd need to make sure with this option that the label made from `stage`, `name`, etc. matches the name of the bucket you already have.

If you have any other suggestions, please let me know!

**Comment by fog1985** [comment]
> To me, it makes sense that the s3 specific parameters would only apply if the s3 bucket was being newly created.
> 
> Unfortunately, even if we wanted to allow updating the CORS of existing buckets, terraform makes that difficult.
> 
> To be able to control the CORS on an s3 bucket in terraform, you need to manage the s3 resource in that module, meaning to accomplish what you're asking you'd need to `terraform import` the bucket into the terraform state of this module. If you're managing that s3 bucket in some other module already, that would be problematic as you never want the same resource managed by multiple terraform modules.
> 
> So in your case, I think the easiest options are to:
> 
> 1. Update the CORS for the origin bucket outside of this module, ideally in some other module that manages your bucket
> 2. Import the bucket state into this module, then do not use the `origin_bucket` var. You'd need to make sure with this option that the label made from `stage`, `name`, etc. matches the name of the bucket you already have.
> 
> If you have any other suggestions, please let me know!

Thank you @dmattia for the valuable advice. 
I have work-around that with `null-resource` dependent on the module `cloudfront_s3_cdn `. 
Which just adds these CORS using `aws cli`.

**Comment by dmattia** [comment]
Sounds great. I think this can be closed then @aknysh
