### ISSUE TITLE
Add label_order feature

### ISSUE THREAD

**Issue by iamaverrick** [cloudposse/terraform-aws-cloudfront-s3-cdn#79]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) in the `#geodesic` channel or visit our [Slack Archive](https://archive.sweetops.com/geodesic/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

Currently the module does not allow the modification of the order of the label. this feature is important to be able to control which way the name is displayed in the name.

## Expected Behavior

would like to be able to add label_order as an argument which is fully controlled by the end user. feature can be found in this module https://registry.terraform.io/modules/clouddrove/s3/aws/0.12.3

**Comment by jamengual** [comment]
we are happy to receive PRs, do you want to give it a try?

**Comment by nitrocode** [comment]
Looks like this is done because there is now a `var.label_order` thanks to this PR https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/pull/103
