### ISSUE TITLE
Changes required on each apply

### ISSUE THREAD

**Issue by cliveza** [cloudposse/terraform-aws-cloudfront-s3-cdn#8]
Hi - This module is great, but each time I run terraform apply it looks like it wants to set and then remove a certificate - just wondering if you know why?

```viewer_certificate.111111111.acm_certificate_arn:            "" => "arn:aws:acm:us-east-1:12121212:certificate/1111111-222222-3333-4444-4444"
viewer_certificate.111111111.cloudfront_default_certificate: "" => "true"
viewer_certificate.111111111.iam_certificate_id:             "" => ""
viewer_certificate.111111111.minimum_protocol_version:       "" => "TLSv1"
viewer_certificate.111111111.ssl_support_method:             "" => "sni-only"
viewer_certificate.222222222.acm_certificate_arn:             "arn:aws:acm:us-east-1:12121212:certificate/1111111-222222-3333-4444-4444" => ""
viewer_certificate.222222222.cloudfront_default_certificate:  "false" => "false"
viewer_certificate.222222222.iam_certificate_id:              "" => ""
viewer_certificate.222222222.minimum_protocol_version:        "TLSv1" => ""
viewer_certificate.222222222.ssl_support_method:              "sni-only" => ""```

**Comment by osterman** [comment]
In my experience, I've seen this happen if the format of your ARN doesn't match the normalized version that AWS or Terraform uses. Can you share the complete plan?

**Comment by cliveza** [comment]
I have a website module that I use to create a prod, staging and dev version of the a static website. 

This website module calls the terraform-aws-cloudfront-s3-cdn module 3 times, once for each environment.

**website.tf file:**
```
data "aws_acm_certificate" "my_domain_com" {
  domain   = "*.my_domain.com"
  statuses = ["ISSUED"]
}

module "frog_website" {
  source              = "../modules/website"
  subdomain           = "frog"
  domain              = "my_domain.com"
  acm_certificate_arn = "${data.aws_acm_certificate.my_domain_com.arn}"
}
```

**website module:**
```
locals {
  name         = "${var.subdomain}.${var.domain}"
  prod_fqdn    = "${local.name}"
  staging_fqdn = "${var.subdomain}-staging.${var.domain}"
  dev_fqdn     = "${var.subdomain}-test.${var.domain}"
}

module "development_website" {
  source              = "git::https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn.git?ref=master"
  namespace           = "my-name-space"
  stage               = "dev"
  name                = "${local.name}"
  aliases             = ["${local.dev_fqdn}"]
  parent_zone_name    = "${var.domain}"
  acm_certificate_arn = "${var.acm_certificate_arn}"
}

module "staging_website" { .......
# same as above
}


module "production_website" { .......
# same as above
}

```

**Comment by osterman** [comment]
Yes, that looks good so far. 

One thing to note: this could return random arns if you have more than one cert issued for `*.my_domain.com`. It is possible to have multiple certs issued for same domain. Have you confirmed you have exactly one?

```
data "aws_acm_certificate" "my_domain_com" {
  domain   = "*.my_domain.com"
  statuses = ["ISSUED"]
}
```

**Comment by cliveza** [comment]
Thanks - you're correct we have multiple certs for that domain, but in different region. 

However I'm sure the identifier I saw (for the certificate) when running `terraform plan` was the same. I'll have to test and see.

**Comment by cliveza** [comment]
OK - I've confirmed, the certificate ARNs are the same, I solved this problem by doing [this](https://github.com/Statflo/terraform-aws-cloudfront-s3-cdn/commit/35a2105ec8dfd4f2a8bb66b3a3ad3015c40d7928): 

For the `cloudfront_default_certificate` parameter the Terraform documentation says 

>  Specify this, acm_certificate_arn, or iam_certificate_id.

Which I presume means you can only specify one and not both together.

**Comment by cliveza** [comment]
Oh - just found this: https://www.terraform.io/docs/configuration/interpolation.html#conditionals

**Comment by cliveza** [comment]
#9 for review - could you do a merge/squash please.

**Comment by osterman** [comment]
That's great! Thanks for submitting the PR. Makes sense. I'll have @aknysh review and if it looks good, merge & tag a new release.

**Comment by aknysh** [comment]
@cliveza 
we merged your changes
https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/releases/tag/0.1.5
thanks again for the contribution
