### ISSUE TITLE
Log Bucket Error in 0.25.0 , 0.26.0 and master

### ISSUE THREAD

**Issue by meabed** [cloudposse/terraform-aws-cloudfront-s3-cdn#87]
Hey awesomes,
Thanks for the great effort, the module is doing great job!
I have found a small issue when using latest version.
 
When applying terraform with  `  logging_enabled = false` it cannot be applied due to the error below in logging the `https://github.com/cloudposse/terraform-aws-s3-log-storage` module 

```
Error: error creating public access block policy for S3 bucket (): InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, PutPublicAccessBlockInput.Bucket.


  on .terraform/modules/cf-s3-cms.logs/main.tf line 81, in resource "aws_s3_bucket_public_access_block" "default":
  81: resource "aws_s3_bucket_public_access_block" "default" {
```

Screen shot

![image](https://user-images.githubusercontent.com/45731/86770799-55617600-c062-11ea-80e7-1856feca621b.png)

Thanks a lot! 👍

**Comment by jamengual** [comment]
do you think you could send us a PR with the fix?

Thanks.

**Comment by meabed** [comment]
Absolutely! Will send it shortly :) thanks 😊

**Comment by meabed** [comment]
@jamengual 
This version needs to be https://github.com/cloudposse/terraform-aws-s3-log-storage/releases/tag/0.12.0
https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/blob/a1ad726664056e37e97147318baa16e9a0cd5a35/main.tf#L149

**Comment by hawkesnc** [comment]
I'm also running into this issue. Looking forward to the merge of your PR: https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/issues/87
