### ISSUE TITLE
S3 Bucket not found

### ISSUE THREAD

**Issue by JohnShortland** [cloudposse/terraform-aws-cloudfront-s3-cdn#90]
## Describe the Bug
Ran using the example from repo and get the following error:

```
Error: Failed getting S3 bucket: NotFound: Not Found
        status code: 404, request id: EAC7428BD0E1699D, host id: rQ8gPW9bBhoBc6IOtIIslXHcioIr3VFwti9wxiPCZ6FqkUn/n2+qvqaVefuhcUzDteJdOavMLSU= Bucket: "BUCKET_NAME.DOMAIN.COM"

  on .terraform/modules/cloudfront_s3_cdn/main.tf line 176, in data "aws_s3_bucket" "selected":
 176: data "aws_s3_bucket" "selected" {
```

This is being ran on an organisation account in eu-west-1

## Expected Behavior
Bucket to be created and cloudfront distro created

## Screenshots

```hcl
module "cloudfront_s3_cdn" {
  source                   = "git::https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn.git?ref=tags/0.26.0"
  namespace                = "${terraform.workspace}"
  stage                    = var.stage
  name                     = "BUCKET_NAME"
  use_regional_s3_endpoint = true
  origin_force_destroy     = true
  cors_allowed_headers     = ["*"]
  cors_allowed_methods     = ["GET", "HEAD", "PUT"]
  cors_allowed_origins     = ["*.${var.domain}"]
  cors_expose_headers      = ["ETag"]
  acm_certificate_arn      = aws_acm_certificate.BUCKET_NAME.arn
  aliases                  = ["BUCKET_NAME.${var.domain}"]
  origin_bucket            = "BUCKET_NAME.${var.domain}"
}
```

## Environment (please complete the following information):
 - OS: WSL
 - Version: 2.0

**Comment by shushry** [comment]
I ran into this also - I think there is some confusion about the parameter "origin_bucket".   If you were like me, you were assuming you could define the name of a NEW bucket to contain your origin, using that parameter.   However, the module wants to name a new bucket FOR you, dynamically, based on the values of namespace, stage, etc.   If you specify "origin_bucket" it's looking for an EXISTING bucket that you might already have out there.    

Docs should be updated to clarify this.

**Comment by nitrocode** [comment]
Yes, the `origin_bucket` is for an existing s3 bucket. I put in a PR to update the description of this variable.
