### ISSUE TITLE
Manually specify existing log buckets

### ISSUE THREAD

**Issue by carvalhovitor2** [cloudposse/terraform-aws-cloudfront-s3-cdn#92]
Module seems to be really handy and has helped me a lot maintaining my infraestructure. Nevertheless, I had to perform some tweaks in order to send the logs to an already-existing s3 bucket. IMHO, I think allowing the user to specify an existing s3 buckets to send logs to would be a nice and easy feature to introduce.

**Comment by joe-niland** [comment]
@carvalhovitor2 would you be able to contribute your tweaks as a PR?

**Comment by carvalhovitor2** [comment]
Sure. Would you prefer if I also updated the README.md with the variables I added in the PR?

**Comment by joe-niland** [comment]
@carvalhovitor2 you just need to make sure the variables have descriptions and then the readme can be rebuilt automatically. Thanks!

**Comment by nitrocode** [comment]
Looks like this has been fixed by PR https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/pull/121 using `var.access_log_bucket_name`
